Add `kManagerDriven` and `kRequired` access modes
OpenAssetIO/OpenAssetIO pull request #1255
Opened 2024-01-31 13:11 UTC by feltech

## Description

Closes #1209

Add the `kRequired` and `kManagerDriven` access modes for use with `managementPolicy`; and rename `ResolveAccess.kWrite` to `kManagerDriven`, for consistency.

- [x] I have updated the release notes.
- [x] I have updated all relevant user documentation.

## Test Instructions

See
- <MediaCreation PR>
- <BAL PR>

2024-02-02 12:23 UTC, elliotcmorris requested changes
Looks grand. Only minor doc comments.

2024-02-07 10:01 UTC, feltech commented on src/openassetio-core/include/openassetio/access.hpp
> +   * @see @ref PolicyAccess.kRequired
Whoops, good spot

2024-02-07 10:05 UTC, feltech commented on src/openassetio-core/include/openassetio/access.hpp
> +   * properties filled for successful publishing of an entity.
I don't think we have any better place to elaborate on this, so I can just expand the docs here.

2024-02-07 11:24 UTC, feltech commented on src/openassetio-core/include/openassetio/hostApi/Manager.hpp
> +   *    you wish to publish for that type of entity.
I don't think that's right. This is the doc for the `managementPolicy`, so providing the  `kRequired` traits requires querying the policy in the first place, only to query the policy again with those traits?

Regardless, the `managementPolicy` docs could do with expanding to make more sense for the new access modes.

2024-02-07 12:53 UTC, feltech commented on RELEASE_NOTES.md
> +  [#1209](https://github.com/OpenAssetIO/OpenAssetIO/issues/1209)
Reworded slightly in b88faff1

2024-02-07 12:54 UTC, feltech commented on doc/doxygen/src/Examples.dox
> + * # publishing, we can `resolve` in `kManagerDriven` mode to
Tweaked as suggested in 9bcc8550

2024-02-07 12:55 UTC, feltech commented on src/openassetio-core/include/openassetio/access.hpp
> +   * properties filled for successful publishing of an entity.
Elaborated in 060c8720. Also see updates in response to https://github.com/OpenAssetIO/OpenAssetIO/pull/1255#discussion_r1475993032

2024-02-07 12:55 UTC, feltech commented on src/openassetio-core/include/openassetio/access.hpp
> +   * @see @ref PolicyAccess.kRequired
Removed in 060c8720

2024-02-07 15:36 UTC, elliotcmorris commented on src/openassetio-core/include/openassetio/hostApi/Manager.hpp
> +   *    you wish to publish for that type of entity.
:facepalm: Oh yeah you're right. I got it in my head this was talking about a publishing action post managementPolicy.

2024-02-07 15:37 UTC, elliotcmorris approved these changes
LGTMSAMWR

2024-02-09 15:33 UTC, merged