Add StubCppManager
OpenAssetIO/OpenAssetIO pull request #1342
Opened 2024-07-02 11:29 UTC by feltech

## Description

Closes #1324. OpenAssetIO now supports C++ plugins. However, the only C++ plugins that currently exist are stubs used in the unit tests, and these are insufficient for testing the usage of C++ plugins by host applications.

So add a simple C++ manager/plugin combination that only supports the minimal required capabilities plus `resolve`.

- [x] I have updated the release notes.
- [x] I have updated all relevant user documentation.

## Reviewer Notes

Also see https://github.com/OpenAssetIO/OpenAssetIO/issues/1340

## Test Instructions

2024-07-04 12:01 UTC, elliotcmorris requested changes

2024-07-05 08:07 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +        std::string propertyValue;
Unfortunately, clang-tidy complains

2024-07-05 11:00 UTC, feltech commented on README.md
> +>   ecosystem.
Not sure about this. "Integrations" is a bit limited - e.g. Jupyter notebooks, template manager plugin. Is there a better phrase?

2024-07-05 11:01 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +              std::distance(cbegin(kCapabilityNames), iter)));
Done as part of 846878c7

2024-07-05 11:02 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +        keyAndValue != cend(settings_)) {
Added a lambda as part of 846878c7

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +   * entry in the result should be imbued will all those traits
Fixed as part of 3262381a

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +   * entry in the result should be imbued will all those traits
Fixed as part of 3262381a

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +          break;
Added a comment in e53333a5

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +      if (const auto& entityRefAndTraitProperties =
Refactored variable names in 8827887d

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +          if (const auto& traitAndProperties = entityRefAndTraitProperties->second.find(traitId);
Refactored variable names in 8827887d

2024-07-05 11:03 UTC, feltech commented on examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
> +  EntityTraitProperties entityTraitProperties_;
Refactored variable names in 8827887d

2024-07-05 11:04 UTC, feltech commented on examples/manager/SimpleCppManager/CMakeLists.txt
> +    if (_parent_project_name STREQUAL "OpenAssetIO" AND
Good spot, simplified in 981b4f97

2024-07-05 11:05 UTC, feltech commented on examples/README.md
> +OpenAssetIO hosts and manager plugins. They cover a large range,
Updated as suggested in c92b97d9

2024-07-05 11:05 UTC, feltech commented on examples/README.md
> +and manager plugins that make use of OpenAssetIO.
Updated as suggested in c92b97d9

2024-07-05 11:06 UTC, feltech commented on examples/manager/SimpleCppManager/README.md
> +
Added some similar text in 736ae804

2024-07-05 13:25 UTC, feltech commented on .github/workflows/integrations.yml
> +        run: echo 'PATH=${{ github.workspace }}/dist/bin' >> $GITHUB_PATH
Removed this and `LD_LIBRARY_PATH` in b40c2133fe43de0a9984eb033026b240589ff1e2 - seems to work still :thinking:

2024-07-08 12:18 UTC, elliotcmorris commented on README.md
> +>   ecosystem.
Just "See some examples" might be better.

But this is so minor you shouldn't bother holding up merging on this tbh. Going to approve, feel free to resolve this leaving it as it is.

2024-07-09 11:36 UTC, merged