Remove deprecated aliases
OpenAssetIO/OpenAssetIO pull request #1370
Opened 2024-07-24 10:22 UTC by feltech

## Description

Closes #1311. We are approaching a v1.0.0 release and plan to have a clean break from compatibility with consumers working with alpha versions of OpenAssetIO.

So remove various deprecated aliases to types and enums that have been moved or renamed.

This required updates to a few downstream projects to bump their minimum MediaCreation dependency to a version that does not make use of deprecated aliases. I.e. 

- https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/118
- https://github.com/OpenAssetIO/Template-OpenAssetIO-Manager-Python/pull/24
- https://github.com/OpenAssetIO/otio-openassetio/pull/23

- [x] I have updated the release notes.
- [ ] ~~I have updated all relevant user documentation.~~

2024-07-24 11:06 UTC, feltech commented
CI will fail until https://github.com/OpenAssetIO/OpenAssetIO-Test-CMake/pull/17 is merged.

2024-07-25 13:09 UTC, foundry-markf requested changes

2024-07-25 13:09 UTC, foundry-markf commented on src/openassetio-core/include/openassetio/typedefs.hpp
> + * namespacest .
Unexpected typo here

2024-07-25 16:12 UTC, foundry-markf approved these changes

2024-07-26 15:18 UTC, merged