[Core] Update Manager to expect EntityReference
OpenAssetIO/OpenAssetIO pull request #567
Opened 2022-08-11 12:58 UTC by feltech

Update tests and docs to use `EntityReference` object workflows.

Since most of the implementation is still in Python, there isn't much in the way of core code changes.

Though I can't help the nagging feeling I've missed something :thinking:

2022-08-15 12:45 UTC, foundrytom requested changes
Good stuff @feltech, great work on the search + updates.  Mainly docs related notes I think, as the policy is a little different now, and so may warrant an alternate approach to the examples.

2022-08-15 16:05 UTC, feltech commented on resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
> +                entity_info = bal.parse_entity_ref(ref.toString())
Added https://github.com/OpenAssetIO/OpenAssetIO/issues/573, is that OK?

2022-08-15 16:58 UTC, feltech commented on doc/src/Examples.dox
> + *
I went with the first option in 0efaac15. I removed all reference to `isEntityReferenceString`.

2022-08-15 16:58 UTC, feltech commented on doc/src/Examples.dox
>   *    raise ValueError(f'"{some_string}" isn't an entity reference.')
Simply removed that exception as part of 153a4629

2022-08-15 16:59 UTC, feltech commented on python/openassetio/hostApi/Manager.py
> +        "isEntityReferenceString" first.
Removed this reference to `isEntityReferenceString`, and instead added a note in its own docs to clarify the intended usage, in 153a4629

2022-08-15 17:01 UTC, feltech commented on doc/src/Examples.dox
> + * this. Below we use @fqref{hostApi.Manager.isEntityReferenceString}
Simply removed the reference to `isEntityReferenceString` in 0efaac15

2022-08-16 08:08 UTC, foundrytom commented on doc/src/Examples.dox
> + *
👍 Think `L106` needs updating to remove "that may be an entity reference to an entity".

2022-08-16 09:51 UTC, feltech commented on doc/src/Examples.dox
> + *
Updated in 276e35a7, I think that's what you meant?

2022-08-16 10:01 UTC, foundrytom commented on doc/src/Examples.dox
> + *
Sorry meant updating the bit on Line 106 that says:

> This example shows how to use the instantiated manager to resolve a string (`some_string`) that may be an entity reference to an entity...

to 

> This example shows how to use the instantiated manager to resolve a string (`some_string`) that references an entity

As we are no longer consciously considering the "may" part.

2022-08-16 10:02 UTC, foundrytom commented on doc/src/Examples.dox
> + *
Ahh its updated in https://github.com/OpenAssetIO/OpenAssetIO/pull/567/files#diff-92209cb683b633be05a90d1e137b02531a50b3935a3b20b4c2e2660ab6a21ba9.

2022-08-16 10:04 UTC, foundrytom approved these changes
I also share your niggling feeling of having forgotten something, but LGTMSAMAYL 👍

2022-08-16 12:25 UTC, merged