Work/850 py resolve convenience
OpenAssetIO/OpenAssetIO pull request #867
Opened 2023-03-30 17:14 UTC by feltech

## Description

Closes #850. Follows on from #849 (not just numerically).

For parity with C++ methods, bind `resolve` convenience overloads to Python.

- [x] I have updated the release notes.
- [x] I have updated all relevant user documentation.

## Test Instructions

Python unit tests added.

2023-03-31 08:04 UTC, foundrytom requested changes
Great stuff, clever trick re: exceptions. 

Will give this a test shortly.

Can we also update `simpleReolver.py` too - I know arguably its current form is probably better suited to what it does, I've just seen it used as a starting point for other code where it's not. As people dont really read the docs, showing the form thats perhaps better suited to more real-world code bases will save people going round the houses for common tasks.

2023-03-31 08:23 UTC, foundrytom commented
Clang 14 has this to say:
```
  136 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|87 col 59| error: the parameter 'pexc' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnin
  137 ||   py::register_exception_translator([](std::exception_ptr pexc) {
  138 ||                                                           ^
  139 ||                                        const             &
  140 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|105 col 30| error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
  141 ||       std::rethrow_exception(std::move(pexc));
```

2023-03-31 08:28 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +        batch_element_error = BatchElementError(error_code, "some string")
> Clang 14 has this to say:
> 
> ```
>   136 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|87 col 59| error: the parameter 'pexc' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnin
>   137 ||   py::register_exception_translator([](std::exception_ptr pexc) {
>   138 ||                                                           ^
>   139 ||                                        const             &
>   140 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|105 col 30| error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
>   141 ||       std::rethrow_exception(std::move(pexc));
> ```

Ooo intereting. CLion's built-in clang-tidy 16 stopped complaining when I added the `std::move`.  This was on Linux though.  Perhaps it's a platform implementation difference with `rethrow_exception`?  Will take a look.

2023-03-31 08:28 UTC, feltech commented
f

> Clang 14 has this to say:
> 
> ```
>   136 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|87 col 59| error: the parameter 'pexc' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnin
>   137 ||   py::register_exception_translator([](std::exception_ptr pexc) {
>   138 ||                                                           ^
>   139 ||                                        const             &
>   140 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|105 col 30| error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
>   141 ||       std::rethrow_exception(std::move(pexc));
> ```

> Clang 14 has this to say:
> 
> ```
>   136 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|87 col 59| error: the parameter 'pexc' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnin
>   137 ||   py::register_exception_translator([](std::exception_ptr pexc) {
>   138 ||                                                           ^
>   139 ||                                        const             &
>   140 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|105 col 30| error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
>   141 ||       std::rethrow_exception(std::move(pexc));
> ```

Ooo intereting. CLion's built-in clang-tidy 16 stopped complaining when I added the `std::move`.  This was on Linux though.  Perhaps it's a platform implementation difference with `rethrow_exception`?  Will take a look.

2023-03-31 16:13 UTC, feltech commented
> > Clang 14 has this to say:
> > ```
> >   136 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|87 col 59| error: the parameter 'pexc' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnin
> >   137 ||   py::register_exception_translator([](std::exception_ptr pexc) {
> >   138 ||                                                           ^
> >   139 ||                                        const             &
> >   140 src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp|105 col 30| error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
> >   141 ||       std::rethrow_exception(std::move(pexc));
> > ```
> 
> Ooo intereting. CLion's built-in clang-tidy 16 stopped complaining when I added the `std::move`. This was on Linux though. Perhaps it's a platform implementation difference with `rethrow_exception`? Will take a look.

Double-checked, and clang-tidy 16 doesn't complain about "passing result of std::move() as a const reference argument".  If I remove the `std::move` then it starts complaining about "only used as a const reference; consider making it a const reference" .

[cppreference](https://en.cppreference.com/w/cpp/error/rethrow_exception) shows that `rethrow_exception` takes its `exception_ptr` by value, so can be moved into as long as `exception_ptr` can be moved.

I found an [isocpp discussion thread](https://groups.google.com/a/isocpp.org/g/std-discussion/c/FVevlnBmbTA) indicating that `exception_ptr` is indeed moveable, and that is dictated by the standard. I confirmed that the libstdc++ 9 implementation on Linux has a move constructor.

Offline we checked that `rethrow_exception` does indeed take its argument by value on MacOS (not sure what std library version that was), as it should. We didn't check that `exception_ptr` is moveable, though.

The weight of evidence seems to suggest that clang-tidy 14 is flagging a false positive.  To be extra sure we could also check that the MacOS implementation of `exception_ptr` has a move constructor.

2023-03-31 16:15 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +        batch_element_error = BatchElementError(error_code, "some string")
✨ inserted in e141f084

2023-03-31 16:15 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +                EntityResolutionErrorBatchElementException,
Good shout, factored out in 5e6f106d

2023-03-31 16:15 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +        assert actual.code == batch_element_error.code
Asserted type in 33b8f471 then refactored into a function as part of 1bd32711

2023-03-31 16:16 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +        assert actual_traitsdatas == some_populated_traitsdatas
Good idea. Used `is` in a bunch more places in b3d46666

2023-03-31 16:16 UTC, feltech commented on src/openassetio-python/tests/package/hostApi/test_manager.py
> +    def test_when_success_out_of_order_then_output_returned_in_order(
Expanded the existing test in 1bd32711, hopefully that's sufficient rather than adding a new test.

2023-03-31 16:17 UTC, foundrytom commented
> The weight of evidence seems to suggest that clang-tidy 14 is flagging a false positive. 

As were on 12 in CI, and thats working, shall we just ignore this for now? Ill test 16 on mac when I can

> To be extra sure we could also check that the MacOS implementation of `exception_ptr` has a move constructor.

Do we need to worry about that too much - iirc it's just saying no move will happen as it thinks its a const-ref, not that its not movable?

2023-03-31 16:21 UTC, feltech commented
> > The weight of evidence seems to suggest that clang-tidy 14 is flagging a false positive.
> 
> As were on 12 in CI, and thats working, shall we just ignore this for now? Ill test 16 on mac when I can
> 
> > To be extra sure we could also check that the MacOS implementation of `exception_ptr` has a move constructor.
> 
> Do we need to worry about that too much - iirc it's just saying no move will happen as it thinks its a const-ref, not that its not movable?

Yeah I suspect 12 just isn't clever enough to have an opinion.

`std::move` is harmless even if it doesn't work, so really not worth worrying about, especially if we're reasonably confident it's correct.

2023-03-31 16:24 UTC, foundrytom commented
> > > The weight of evidence seems to suggest that clang-tidy 14 is flagging a false positive.
> > 
> > 
> > As were on 12 in CI, and thats working, shall we just ignore this for now? Ill test 16 on mac when I can
> > > To be extra sure we could also check that the MacOS implementation of `exception_ptr` has a move constructor.
> > 
> > 
> > Do we need to worry about that too much - iirc it's just saying no move will happen as it thinks its a const-ref, not that its not movable?
> 
> Yeah I suspect 12 just isn't clever enough to have an opinion.
> 
> `std::move` is harmless even if it doesn't work, so really not worth worrying about, especially if we're reasonably confident it's correct.

Awesomesauce, thanks for all the investigations.

2023-03-31 16:26 UTC, foundrytom approved these changes
Epic, so great to see how much more readable the control flow is in Simple Resolver, and how closely it matches C++.

2023-04-03 11:26 UTC, feltech commented
^ fixed an errant newline that `black` was complaining about.

2023-04-03 11:46 UTC, merged